apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      project: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        project: {{ .Values.app.name }}
    spec:
      containers:
        - name : {{ .Values.app.name }}
          image: {{ .Values.app.repo }}/{{ .Values.app.name }}:{{ .Values.app.version }}
          ports:
            - containerPort: 80