apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    project: {{ .Values.app.name }}
  ports:
    - name: {{ .Values.app.name }}
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer